### ISSUE TITLE
Does SDM work for ArcMap 10.4?

### ISSUE THREAD

**Issue by cml1227** [gtkfi/ArcSDM#8]
I'm getting an error that says <type.'exceptions.AttributeError'>: 'NoneType object has no attribute 'lower.'

All of my rasters are in the same projection and in meters and my evidential theme and study grid area are the same size. Do you know why this error is happening?

**Comment by trotor** [comment]
Hi and thanks for your feedack. It should work on 10.4 but we have only tested against 10.3 and 10.4.1 - in which tool do you get the error?

T

**Comment by cml1227** [comment]
This was in the calculate weights tool. I also tried using in 10.1 and got
the same error.

Thanks!

**Comment by trotor** [comment]
Can you send screenshot of your inputs etc. to us via e-mail or attach them with detail here? For some reason there are some very strict limits with the default environment variables. But it is tested through with the demo data and should work.

you could send the image to tero.ronkko@gtk.fi

**Comment by cml1227** [comment]
Here is a dropbox link
<https://www.dropbox.com/sh/m5ewpcq0qeu3afm/AADeBA77qINDwM8bGtKdsYNaa?dl=0>
to the two input files we were testing it with. We
clipped ap15v4_A1520_M_adj to central_african_vegetation map and also
created a raster file of all 1's of the same size for the study area file.
We also projected them into Africa Albers Equal Area Conic projection
system.

I don't have the clipped and projected version of these files on my
computer right now but am waiting for someone to send them to me and will
send to you once I have them!

**Comment by cml1227** [comment]
Hi,


thanks for the link, I will take a look on monday. I have been very busy last months on other tasks and haven't done too much on the tool lately.  I know the documentation is still work in progress so it could be "problem" with just incompatible data.


Have a great weekend!?


T


________________________________

**Comment by cml1227** [comment]
Thanks, I appreciate it!

Also, below is the link that has the clipped and projected study area and
two evidential theme rasters as well as the training points:

https://www.dropbox.com/sh/fw8y5h1gkzp4b3g/AABKVc2kCNZqsCEP4qdDZgzca?dl=0

**Comment by trotor** [comment]
Thanks for the data - I took a quick look and it seems that there is atleast some errors on .tif raster type handling. Need some syntax fixing in our environment even to start working on the actual error you mention. I will keep you updated here.

**Comment by trotor** [comment]
After fixing geodatabase not wanting "." characters:

============================== arcsdm values ==============================
Workspace:           C:\Users\tronkko.GTK\Documents\ArcGIS\Default.gdb
Scratch workspace:   C:\Users\tronkko.GTK\Documents\ArcGIS\Default.gdb
Mask:                "studyarea.tif" and it is RasterLayer
Mask size:           14991564.0
Cell Size:           1000.0
# Training Sites:    778
Unit Cell Area:      1.0km^2, Cells in area: 14991564.0 
Prior Probability:   0.000052
Training Set:        C:\Users\tronkko.GTK\Dropbox\delivered_20161209\VAC_test_clip_prj.shp
Study Area Raster:   C:\Users\tronkko.GTK\Dropbox\delivered_20161209\studyarea.tif
Study Area Area:     14991564.0km^2
Map Units:           meter
========== Calculate weights ==========
Creating table:      %WORKSPACE%\Vegtif_WD (Descending)
Done creating table.
Completed script CalculateWeightsTool...
Succeeded at Mon Dec 12 10:08:30 2016 (Elapsed Time: 7,92 seconds)

So Calculate Weights tool completes with my environment settings.

One of the not so obvious possibilities could be "Raster Analysis Cell Size" which has to be "As specified below" currently. Could this be problem at the moment? What do you have there?

**Comment by cml1227** [comment]
Thanks so much for looking into this!

Just to confirm - you were using ArcMap 10.4?

I don't have access to a computer with ArcMap at the moment but I don't
recall seeing an option for 'as specified below.' We had an empty text box
to enter a size and I think we were using .5 km and also tried 1 km. Do you
mind sending me a screenshot of where you select 'as specified below'?

Thanks!

**Comment by trotor** [comment]
Unfortunately I currently only have access to 10.4.1 ArcGis - I also did some fixing there and it should now accept any number (including floating points) or selecting some layer (which converts it to number). MAX OF or MIN OF don't still work. Sorry.

https://dl.dropboxusercontent.com/u/10684431/sdmtmp/calculateweights1.png
https://dl.dropboxusercontent.com/u/10684431/sdmtmp/cellsize1.png
https://dl.dropboxusercontent.com/u/10684431/sdmtmp/cellsize2.png

p.s. We are planning to separate example data and just the toolbox to make downloading and updating it easier for users. It is already much easier with Github desktop app, but whole package download size is inconvenient. But I did fix some simple things on the code regarding this issue and perhaps they were repaired.

**Comment by cml1227** [comment]
Hmm I am also using 10.4.1 and am following the parameters of the pictures
you sent but am still getting the below error. Perhaps I am not downloading
the correct extension. I am taking from this website:
http://www.ige.unicamp.br/sdm/ArcSDM10/download.php. Is there somewhere
else I should get it from?


Executing: CalculateWeights Veg.tif # VAC_test_clip_prj Categorical
"C:\Users\chl587\Desktop\13 dec 2016\test.dbf" 2 0.5 -99
Start Time: Tue Dec 13 11:15:06 2016
Running script CalculateWeights...
Workspace: C:\Users\chl587\Documents\ArcGIS\Default.gdb
Scratch workspace: C:\Users\chl587\Documents\ArcGIS\Default.gdb
Output Coordinate System not set
GP ERRORS:


PYTHON ERRORS:
Traceback Info:
  File "C:\Users\chl587\Desktop\13 dec 2016\SDM\Scripts\SDMValues.py", line
83, in getMapUnits
    raise Exception

Error Info:
    <type 'exceptions.Exception'>:

PYTHON ERRORS:
Traceback Info:
  File "C:\Users\chl587\Desktop\13 dec 2016\SDM\Scripts\SDMValues.py", line
31, in appendSDMValues
    mapUnits = getMapUnits(gp).lower().strip()

Error Info:
    <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute
'lower'

GP ERRORS:
Executing: GetRasterProperties Veg.tif VALUETYPE #
Start Time: Tue Dec 13 11:15:06 2016
Value type = Unsigned Integer
Succeeded at Tue Dec 13 11:15:06 2016 (Elapsed Time: 0.01 seconds)

PYTHON ERRORS:
Traceback Info:
  File "C:\Users\chl587\Desktop\13 dec 2016\SDM\Scripts\NewWtsofEvIter.py",
line 171, in <module>
    SDMValues.appendSDMValues(gp,  Unitarea, TrainingSites)

Error Info:
    <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute
'lower'

Failed script CalculateWeights...

Traceback (most recent call last):
  File "C:\Users\chl587\Desktop\13 dec 2016\SDM\Scripts\NewWtsofEvIter.py",
line 171, in <module>
    SDMValues.appendSDMValues(gp,  Unitarea, TrainingSites)
  File "C:\Users\chl587\Desktop\13 dec 2016\SDM\Scripts\SDMValues.py", line
31, in appendSDMValues
    mapUnits = getMapUnits(gp).lower().strip()
AttributeError: 'NoneType' object has no attribute 'lower'

Failed to execute (CalculateWeights).
Failed at Tue Dec 13 11:15:06 2016 (Elapsed Time: 0.09 seconds)

**Comment by cml1227** [comment]
So I downloaded the extension straight from github and now am getting this
error:

Executing: CalculateWeightsTool veg_project # VAC_test_clip_prj Categorical
C:\Users\chl587\Documents\ArcGIS\Default.gdb\veg_project_WC 2 1 -99
Start Time: Tue Dec 13 11:29:47 2016
Running script CalculateWeightsTool...
Reloaded arcsdm modules

============================== arcsdm values  ==============================
Workspace:           C:\Users\chl587\Documents\ArcGIS\Default.gdb
Scratch workspace:   C:\Users\chl587\Documents\ArcGIS\Default.gdb
Mask:                "studyarea.tif" and it is RasterLayer
SDMVALUES + GP ERRORS:


PYTHON ERRORS:
Traceback Info:
  File "C:\Users\chl587\Desktop\13 dec
2016\ArcSDM-master\Toolbox\arcsdm\sdmvalues.py", line 209, in getMapUnits
    arcpy.adderror('Output Coordinate System not set')

Error Info:
    <type 'exceptions.AttributeError'>: 'module' object has no attribute
'adderror'

  File "C:\Users\chl587\Desktop\13 dec
2016\ArcSDM-master\Toolbox\arcsdm\sdmvalues.py", line 74, in getMaskSize
    mapUnits = getMapUnits().lower().strip()

  File "C:\Users\chl587\Desktop\13 dec
2016\ArcSDM-master\Toolbox\arcsdm\sdmvalues.py", line 132, in
appendSDMValues
    gp.addMessage( "%-20s %s" %( "Mask size:", str(getMaskSize())  ));

'module' object has no attribute 'adderror'
GPMEs: 0
CW - PYTHON ERRORS:
Traceback Info:
  File "C:\Users\chl587\Desktop\13 dec
2016\ArcSDM-master\Toolbox\arcsdm\calculateweights.py", line 205, in
Calculate
    arcsdm.sdmvalues.appendSDMValues(gp,  Unitarea, TrainingSites)

Error Info:
    <function format_exc at 0x21400030>

Unexcpected exception caught
Traceback
  File "C:\Users\chl587\Desktop\13 dec
2016\ArcSDM-master\Toolbox\arcsdm\common.py", line 45, in execute_tool
    func(self, parameters, messages)

Error Info:
'module' object has no attribute 'adderror'
ArcPy ERRORS:


Completed script CalculateWeightsTool...
Failed to execute (CalculateWeightsTool).
Failed at Tue Dec 13 11:29:47 2016 (Elapsed Time: 0.43 seconds)

**Comment by cml1227** [comment]
Sorry for the barrage of emails. I was able to figure it out! Thanks very
much for all your help with this!

**Comment by trotor** [comment]
I am very glad to hear that and we would be very grateful if you continue to send us feedback and questions in the future, if you have any.   From the first of the new reports it seems like there are some typos in my code too. Will fix them soon.   I will be separating the demo data (300MB) from the toolbox (2MB) so the download will be a bit quicker. And perhaps I will implement somekind of versioning system.
